### ISSUE TITLE
Null ref exception when running tests on CoreClr x64 version and Linux OS

### ISSUE THREAD

**Issue by kichalla** [xunit/dnx.xunit#45]
I get a Null ref exception when doing a `dnx . test`. Following are the details:

```
kiran@kiran-VirtualBox:~/github/caching/test/Microsoft.Framework.Caching.SqlServer.Tests$ dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-beta6-12120
 Type:         CoreCLR
 Architecture: x64
 OS Name:      Linux

kiran@kiran-VirtualBox:~/github/caching/test/Microsoft.Framework.Caching.SqlServer.Tests$ dnx . test
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
kiran@kiran-VirtualBox:~/github/caching/test/Microsoft.Framework.Caching.SqlServer.Tests$ 

```

**Comment by bradwilson** [comment]
Which version of the runner are you using? Are you building it from source? We have not shipped anything that supports DNX Beta 6 yet.

**Comment by kichalla** [comment]
I am using `xunit.runner.dnx/2.1.0-beta2-build79`

> We have not shipped anything that supports DNX Beta 6 yet.

Ok..sure...I was using it with Beta 6

**Comment by kichalla** [comment]
@bradwilson Pointing to Xunit night builds fixed the issue for me..thanks!
