### ISSUE TITLE
MissingMethodException when running against beta7 runtime

### ISSUE THREAD

**Issue by AlekseyMartynov** [xunit/dnx.xunit#53]
On both `CLR-x86-1.0.0-beta7-12264` and `CoreCLR-x86-1.0.0-beta7-12264` (installed by `dnvm install latest -u`):

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.Framework.Runtime.ILibraryInformation> Microsoft.Framework.Runtime.ILibraryManager.GetReferencingLibraries(System.String)'.
   at Xunit.Runner.Dnx.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

**Comment by bradwilson** [comment]
Dup of #51.
